version: "2"

services:
  nexus:
    restart: always
    image: sonatype/nexus
    container_name: nexus-server
    volumes:
      - "/srv/nexus/nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    network_mode: "bridge"
    environment:
      TZ: "Europe/Rome"
