version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    links:
      - registry:registry
    volumes:
      - /srv/registry/auth/htpasswd:/etc/nginx/conf.d/htpasswd:ro
      - /srv/registry/certs:/etc/nginx/ssl
      - /srv/registry/conf/nginx.conf:/etc/nginx/nginx.conf:ro

  registry:
    restart: always
    image: registry:2.6.0
    ports:
      - 127.0.0.1:5000:5000
    environment:
      TZ: Europe/Rome
    volumes:
      - /srv/registry/data:/var/lib/registry
#      - /srv/registry/conf/config.yml:/etc/docker/registry/config.yml